global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: flower
    static_configs:
      - targets: ['flower:5555']
  - job_name: rabbitmq
    static_configs:
      - targets: ['rabbitmq:15692']