tasks:
 - name: (mongoDB + RabbitMQ + Redis + Celery + Flower)
   command: |
      docker-compose up
 - name: backend
   command: | 
      cd api
      npm i
      npm run debug
 - name: frontend
   command: | 
      cd frontend
      npm i
      npm start
vscode:
  extensions:
    - rangav.vscode-thunder-client
    - esbenp.prettier-vscode
    - ms-python.python

ports:
  - name: Api
    description: Backend API
    port: 3000
    visibility: public
  - name: Grafana
    description: Grafana Dashboards
    port: 3002
    onOpen: open-browser
  - name: Flower
    description: Flower Celery
    port: 5555
    onOpen: open-browser
