tasks:
 - name: (mongoDB + RabbitMQ + Redis)
   command: |
      docker-compose up
 - name: celery
   command: |
      cd workers
      pip install -r requirements.txt
      celery -A main worker --loglevel=INFO -Q dynamofl -n dynamofl --concurrency 5
 - name: celery-flower
   command: | 
      cd workers
      pip install -r requirements.txt
      export FLOWER_UNAUTHENTICATED_API=true && celery -A main flower --broker_api=http://dynamofl:dynamofl@localhost:15672/api/vhost
 - name: backend
   command: | 
      cd api
      npm i
      npm run debug
 - name: frontend
   command: | 
      cd frontend
      npm i
      npm start
vscode:
  extensions:
    - rangav.vscode-thunder-client
    - esbenp.prettier-vscode
