version: '3'
services:
  mongo:
    image: mongo
    volumes:
      - ./utilities-data/mongodb:/data/db
    ports:
      - "27017:27017"
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672" # RabbitMQ Management UI
    environment:
      RABBITMQ_DEFAULT_USER: dynamofl
      RABBITMQ_DEFAULT_PASS: dynamofl
    volumes:
      - ./utilities-data/rabbitmq:/var/lib/rabbitmq
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    volumes: 
      - ./utilities-data/cache:/data