version: '3'
services:
  mongo:
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  rabbitmq:
    image: rabbitmq:3.8
    ports:
      - "5672:5672"
      - "15672:15672" # RabbitMQ Management UI
    environment:
      RABBITMQ_DEFAULT_USER: dynamofl
      RABBITMQ_DEFAULT_PASS: dynamofl
    volumes:
      - ./rabbitmq-data:/var/lib/rabbitmq